title: Agile Methods & Tools
description: Method and tool collection for working in an agile world.
theme: just-the-docs

url: https://SaschaLucius.github.io/methods-and-tools

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
